In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
df_cards = pd.read_csv("base_cards.csv",sep = ";")

In [107]:
df_cards.head()

  ﻿Suit Face  N_val  C_val
0     H    A     11     -1
1     H    K     10     -1
2     H    Q     10     -1
3     H    J     10     -1
4     H   10     10     -1

In [108]:
def gen_shoe(df_cards,No_decks):
    shoe = df_cards
    for n1 in range(1,int(np.floor(No_decks))):
        shoe = pd.concat([shoe,df_cards]).reset_index(drop=True)
    
    if No_decks % 1.0 != 0.0:
        extra = df_cards.sample(frac=1).reset_index(drop=True)[0:(int((No_decks % 1.0)*52))]
        shoe = pd.concat([shoe,extra]).reset_index(drop=True)
        
    shoe = shoe.sample(frac=1).reset_index(drop=True)
    return shoe

In [109]:
def multi_shoe(df_cards,No_shoes,Decks_per_shoe):
    df_AC = gen_shoe(df_cards,Decks_per_shoe)
    df_AC["Shoe"] = 1
    for n1 in range(1,int(No_shoes)):
        df_new = gen_shoe(df_cards,Decks_per_shoe)
        df_new["Shoe"] = n1 + 1             
        df_AC = pd.concat([df_AC,df_new]).reset_index(drop=True)
    return df_AC

In [126]:
df_BSv = pd.read_csv("BS_Value.csv")
df_BSp = pd.read_csv("BS_Pair.csv")

In [114]:
N_hands = 1
N_p = 3
No_decks = 7

In [122]:
hand = 1
c0 = 0
df_shoe = gen_shoe(df_cards,No_decks)
df_shoe["Player"] = ""
df_shoe["hand"] = 0
h_dict = {}

while hand < N_hands + 1:
    
    # initiate hand parameters
    LB = c0
    
    # Deal 
    
    for n1 in range(1,N_p+1):
        df_shoe.loc[c0,"Player"] = "P" + str(n1)
        df_shoe.loc[c0+1,"Player"] = "P" + str(n1)
        df_shoe.loc[c0,"hand"] = hand
        df_shoe.loc[c0+1,"hand"] = hand
        
        
        
        h_dict.update({"P" + str(n1):{
                    "Score":sum(df_shoe.loc[c0:c0+1,"N_val"]),
                    "Soft":pd.Series("A").isin(df_shoe.loc[c0:c0+1,"Face"])[0],
                    "Splitable":df_shoe.loc[c0,"Face"] ==  df_shoe.loc[c0+1,"Face"]
                }})
        c0 += 2
    
    D_ind = c0 # index of heads up dealer card
    DV_i = df_shoe.loc[c0,"N_val"] 
    
    df_shoe.loc[c0,"Player"] = "Dealer"
    df_shoe.loc[c0+1,"Player"] = "Dealer"
    df_shoe.loc[c0,"hand"] = hand
    df_shoe.loc[c0+1,"hand"] = hand
    
    c0 += 2
    
    # Player decisions
    
    for n1 in range(1,N_p+1):
        
        
        
        
        
    
    
    
    
    df_hand = df_shoe[LB:c0]
    
    #for n1 in range(1,N_p+1):
        
    
    
    
    hand += 1

In [123]:
h_dict

{'P1': {'Score': 16, 'Soft': False, 'Splitable': False},
 'P2': {'Score': 11, 'Soft': False, 'Splitable': False},
 'P3': {'Score': 14, 'Soft': False, 'Splitable': False}}

In [120]:
(df_shoe.loc[c0:c0+1,"Face"])

6    2
7    9
Name: Face, dtype: object

In [121]:
df_shoe

    ﻿Suit Face  N_val  C_val  Player  hand
0       D    3      3      1      P1     1
1       C    6      6      1      P1     1
2       H    Q     10     -1      P2     1
3       D    6      6      1      P2     1
4       D    2      2      1      P3     1
5       S    5      5      1      P3     1
6       H    2      2      1  Dealer     1
7       D    9      9      0  Dealer     1
8       C    7      7      0             0
9       C    9      9      0             0
10      S    Q     10     -1             0
11      S    9      9      0             0
12      D    6      6      1             0
13      H    J     10     -1             0
14      C    J     10     -1             0
15      H    Q     10     -1             0
16      D   10     10     -1             0
17      S   10     10     -1             0
18      H    6      6      1             0
19      H    3      3      1             0
20      H    2      2      1             0
21      C   10     10     -1             0
22      S    J     10     -1             0
23      C    6      6      1             0
24      S    4      4      1             0
25      S    6      6      1             0
26      C    5      5      1             0
27      S    9      9      0             0
28      C    3      3      1             0
29      H    9      9      0             0
..    ...  ...    ...    ...     ...   ...
334     C    A     11     -1             0
335     H    4      4      1             0
336     D    8      8      0             0
337     D    4      4      1             0
338     S    3      3      1             0
339     S    A     11     -1             0
340     H    9      9      0             0
341     H    2      2      1             0
342     D    A     11     -1             0
343     D    Q     10     -1             0
344     H    5      5      1             0
345     S   10     10     -1             0
346     D   10     10     -1             0
347     C    9      9      0             0
348     H    2      2      1             0
349     S    5      5      1             0
350     D    K     10     -1             0
351     C    A     11     -1             0
352     H    J     10     -1             0
353     D    K     10     -1             0
354     C    5      5      1             0
355     D    9      9      0             0
356     C    6      6      1             0
357     S    K     10     -1             0
358     D    J     10     -1             0
359     H    5      5      1             0
360     D    3      3      1             0
361     C    Q     10     -1             0
362     S    K     10     -1             0
363     S    4      4      1             0

[364 rows x 6 columns]

In [30]:
df = df.sample(frac=1).reset_index(drop=True)
df

   ﻿Suit Face  N_val  C_val
0      D    4      4      1
1      H    9      9      0
2      S    7      7      0
3      S    8      8      0
4      D    6      6      1
5      S   10     10     -1
6      C    3      3      1
7      H    2      2      1
8      H    8      8      0
9      S    4      4      1
10     D    A     11     -1
11     S    A     11     -1
12     C    A     11     -1
13     S    Q     10     -1
14     S    2      2      1
15     H   10     10     -1
16     H    J     10     -1
17     S    9      9      0
18     C    6      6      1
19     C    9      9      0
20     C    Q     10     -1
21     D    J     10     -1
22     H    K     10     -1
23     C    8      8      0
24     D    3      3      1
25     C    J     10     -1
26     S    3      3      1
27     D   10     10     -1
28     H    6      6      1
29     C    4      4      1
30     C    K     10     -1
31     S    6      6      1
32     H    7      7      0
33     C    5      5      1
34     S    5      5      1
35     H    A     11     -1
36     S    K     10     -1
37     D    K     10     -1
38     D    5      5      1
39     D    8      8      0
40     H    Q     10     -1
41     H    4      4      1
42     H    3      3      1
43     H    5      5      1
44     D    9      9      0
45     C    2      2      1
46     D    Q     10     -1
47     C    7      7      0
48     C   10     10     -1
49     S    J     10     -1
50     D    7      7      0
51     D    2      2      1